version: '2'
services:
  dewpointvc:
    image: dewpointvc
    build:
      context: .
      dockerfile: docker/dewpointvc/Dockerfile
    privileged: true
    devices:
      - /dev/gpiomem
    ports:
      - 1022:22
    depends_on:
      - influxdb
    environment:
      - DEWPOINTVC_INFLUXDB_ORG=${DEWPOINTVC_INFLUXDB_ORG}
      - DEWPOINTVC_INFLUXDB_BUCKET=${DEWPOINTVC_INFLUXDB_BUCKET}
      - DEWPOINTVC_INFLUXDB_TOKEN=${DEWPOINTVC_INFLUXDB_TOKEN}
      - DEWPOINTVC_INFLUXDB_HOST=influxdb
      - DEWPOINTVC_INFLUXDB_PORT=8086
    restart: always
  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${DEWPOINTVC_INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${DEWPOINTVC_INFLUXDB_PASSWORD}
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${DEWPOINTVC_GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${DEWPOINTVC_GF_ADMIN_PASSWORD}
    restart: always
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
