version: '2'
services:
  dewpointvc:
    image: dewpointvc
    build:
      context: .
      dockerfile: docker/dewpointvc/Dockerfile
    privileged: true
    volumes:
      - dewpointvc_persistence:/dewpointvc_persistence/
    devices:
      - /dev/gpiomem
    ports:
      - 1022:22
      - 5000:5000
    depends_on:
      - influxdb
    environment:
      - DEWPOINTVC_INFLUXDB_ORG=${DEWPOINTVC_INFLUXDB_ORG}
      - DEWPOINTVC_INFLUXDB_BUCKET=${DEWPOINTVC_INFLUXDB_BUCKET}
      - DEWPOINTVC_INFLUXDB_TOKEN=${DEWPOINTVC_INFLUXDB_TOKEN}
      - DEWPOINTVC_INFLUXDB_HOST=influxdb
      - DEWPOINTVC_INFLUXDB_PORT=8086
      - DEWPOINTVC_CONFIG_PATH=/dewpointvc_persistence/config.json
    restart: always
  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${DEWPOINTVC_INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${DEWPOINTVC_INFLUXDB_PASSWORD}
    restart: always
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  dewpointvc_persistence:
